# Generated by Django 3.0.8 on 2020-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200805_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('DE', 'Deutsch'), ('UA', 'Ukrainian'), ('FR', 'French'), ('JP', 'Japanese')], default='en', help_text="The book's natural language (e.g. English, French, Japanese etc.)", max_length=2),
        ),
    ]
